### ISSUE TITLE
Suggestion: Make Artificer's and Rex's M1 Travel Faster

### ISSUE THREAD

**Issue by Undead-Tech** [MapleWheels/RoR2_QoLChanges#14]
Some times it can be harder to hit far away/moving mobs (especially on eclipse) because of how slow Artificer's Fireballs and Rex's Needles(?) travel. Would be a nice QoL if they traveled faster.

**Comment by MapleWheels** [comment]
It's part of the balancing of Artificer's kit. If you can land every shot on her, she's a bit too strong actually. Same thing for REX,  it's part of the skill in the game.
