### ISSUE TITLE
Config not generating on version 0.4.1

### ISSUE THREAD

**Issue by breadguyyy** [MapleWheels/RoR2_QoLChanges#15]
Using Windows 10, latest version
I also have the latest version of Bepinex, R2API, Bepinex Extensions, and QOL changes.
[LogOutput.log](https://github.com/MapleWheels/RoR2_QoLChanges/files/5320143/LogOutput.log)

**Comment by Undead-Tech** [comment]
The plugin is not loading that's why, I just posted a report on this.

**Comment by breadguyyy** [comment]
oh oops i didnt see your report, i was sent here from discord

**Comment by MapleWheels** [comment]
Closed. Duplicate of #16 .
