### ISSUE TITLE
Bug: Error While Scanning Plugin/Failing To Load

### ISSUE THREAD

**Issue by Undead-Tech** [MapleWheels/RoR2_QoLChanges#16]
I got to commencement when I realized Arti wasn't gaining fireballs, looked in the console and saw It was failing to load the plugin.
[LogOutput.log](https://github.com/MapleWheels/RoR2_QoLChanges/files/5320150/LogOutput.log)

**Comment by MapleWheels** [comment]
What operating system are you on and what version?

**Comment by Undead-Tech** [comment]
Windows 10, 64bit latest update as far as i know.

**Comment by MapleWheels** [comment]
Okay thanks. I'm having issues reproducing this on my machine so this might take a bit of time.

**Comment by Undead-Tech** [comment]
I'll check for updates just incase but im pretty sure I'm on the latest.

**Comment by breadguyyy** [comment]
same for me windows 10, 64 bit, latest version

**Comment by Undead-Tech** [comment]
It seems I do have an update and it didn't tell me, I'll report back in a few minutes.

**Comment by MapleWheels** [comment]
Do you guys have all of the dependencies? For example:
https://thunderstore.io/package/MapleWheels/BepInExExtensions/

**Comment by breadguyyy** [comment]
yes, i have the latest version of bepinex, r2api, bepinex extensions, and qol changes itself

using r2modman

**Comment by MapleWheels** [comment]
Just check your r2 profile and confirm. I can reproduce the issue by deleting my BepInEx.Extensions dll.

**Comment by breadguyyy** [comment]
![ScreenShot_20201002171728](https://user-images.githubusercontent.com/21149431/94970686-32b0f300-04d3-11eb-9dbe-24b2e439ac30.png)

**Comment by MapleWheels** [comment]
Thanks, I just confirmed this myself, I'm running through this problem right now in the development chat. It's a weird interaction with r2modman where BE isn't loading one of the dependencies of my mod and so it's failing when R2API tries to resolve the types.

**Comment by breadguyyy** [comment]
good catch, thanks for looking into it

**Comment by MapleWheels** [comment]
I've found the issue and I'll push a fix soon. It's caused by BepInEx unloading my BepInEx.Extensions library because it sits in it's own folder and doesn't think anything needs it.  The workaround is to add a skeleton/empty plugin to the library to keep it loaded.

**Comment by Undead-Tech** [comment]
Ok, glad you found the cause/fix.

**Comment by Undead-Tech** [comment]
Also sorry, went afk for a sec while updates download. Not needed now I suppose but yes, I use r2modman.

**Comment by MapleWheels** [comment]
Update pushed for both the library and the mod.

**Comment by Undead-Tech** [comment]
Ok, just downloaded. Can confirm its working now
