### ISSUE TITLE
Warbanner buff throwing lots of errors for clients

### ISSUE THREAD

**Issue by breadguyyy** [MapleWheels/RoR2_QoLChanges#19]
I know you're on hiatus and I hope you're doing well, but I figured I'd keep this here for organization's sake.

caught this trying to debug an issue with sniper, looks like it may be an issue with minirpclib.

here's the full client log: https://cdn.discordapp.com/attachments/562468922557726721/783413498050379906/message.txt

full host log (didn't see anything in this one relating to the issue):
https://cdn.discordapp.com/attachments/729436716900941884/783399001054773290/message.txt

**Comment by TBN-MapleWheels** [comment]
Hey! I'm back now. This will be addressed in the rewrite which I'm hoping to have released by tomorrow or Monday next week.
