### ISSUE TITLE
Strange Fresh Meat\Burn interaction

### ISSUE THREAD

**Issue by Post34** [MapleWheels/RoR2_QoLChanges#6]
Basically, i noticed that when you have a regen buff from Fresh Meat and burn DoT (maybe any other DoT's) at the same time, your health start to replenish super fast. I made a small video to demonstrate that 
[https://www.youtube.com/watch?v=P6iz-5KEyXg&feature=youtu.be&ab_channel=PostAl](https://www.youtube.com/watch?v=P6iz-5KEyXg&feature=youtu.be&ab_channel=PostAl)

**Comment by Post34** [comment]
By the way, Artificer M1 is still broken :) Just try to run the game with and without your mod. Differences with her starting CD is very noticeable.

**Comment by MapleWheels** [comment]
So, embarrassingly enough. The fix to artificer's M1 was undone by Git because of a stupid sync fail between my laptop and my desktop. It's been re-fixed and is set for 0.3.1.

This bug with Fresh Meat is also fixed for the new release very shortly.
