### ISSUE TITLE
A bug that occured while playing

### ISSUE THREAD

**Issue by fwenny** [MapleWheels/RoR2_QoLChanges#8]
Hi. I had this in my console. It appeared multiple times throughout the run:

[Error  : Unity Log] InvalidOperationException: Collection was modified; enumeration operation may not execute.
Stack trace:
System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
RoR2QoLChanges.Additions.Mechanics.WarbannerBuffHelper.GetWarbannerAttackSpeedModifier (UnityEngine.Vector3 selfPosition) (at <8dc5b52c9d484f039c1a47c186238905>:0)
RoR2QoLChanges.Patches.Items.MMH_WarbannerChanges.ApplyWarbannerChanges (On.RoR2.CharacterBody+orig_RecalculateStats orig, RoR2.CharacterBody self) (at <8dc5b52c9d484f039c1a47c186238905>:0)
DMD<>?-1085021440.Hook<RoR2.CharacterBody::RecalculateStats>?274121344 (RoR2.CharacterBody ) (at <99d826fbfb2d4994a4ea3fa91a251cc1>:0)
DMD<>?-1085021440.Trampoline<RoR2.CharacterBody::RecalculateStats>?1298015232 (RoR2.CharacterBody ) (at <e31df49fbf57421aad2a385e31c22a86>:0)
Rein.RogueWispPlugin.Main.RecalculateStats_On (ReinCore.HooksCore+RoR2+CharacterBody+RecalculateStats+Orig orig, RoR2.CharacterBody self) (at <303810a2b0bf4a69aa9f57986f34d3e0>:0)
DMD<>?-1085021440.Hook<RoR2.CharacterBody::RecalculateStats>?-336138240 (RoR2.CharacterBody ) (at <6b28fbb63a7444ec9e7b6c76fe2ee7b0>:0)
DMD<FixedUpdate>?-1085021440._RoR2_CharacterBody::FixedUpdate (RoR2.CharacterBody this) (at <6e500a4be8b44e73bb86fb1739bf9901>:0)
DMD<>?-1085021440.Trampoline<RoR2.CharacterBody::FixedUpdate>?-276511744 (RoR2.CharacterBody ) (at <7b37cab1359249998845d731aca4d1b0>:0)
ThinkInvisible.ClassicItems.GoldenGun.On_CBFixedUpdate (On.RoR2.CharacterBody+orig_FixedUpdate orig, RoR2.CharacterBody self) (at <f4375b48ede14685b2bb4443cb047c6d>:0)
DMD<>?-1085021440.Hook<RoR2.CharacterBody::FixedUpdate>?714426112 (RoR2.CharacterBody ) (at <9b224caef08f4ba9a9a34f31467c13cd>:0)
DMD<>?-1085021440.Trampoline<RoR2.CharacterBody::FixedUpdate>?661853184 (RoR2.CharacterBody ) (at <8ecfe109b7b7415ab368d97eb612cb6f>:0)
ReinGeneralFixes.Main.FixedUpdate_On (ReinCore.HooksCore+RoR2+CharacterBody+FixedUpdate+Orig orig, RoR2.CharacterBody self) (at <01349d8c86e8416aa123897eeba1d962>:0)
DMD<>?-1085021440.Hook<RoR2.CharacterBody::FixedUpdate>?-2122506624 (RoR2.CharacterBody ) (at <e4909ee0de1547c497edd6508ce30c65>:0)
DMD<>?-1085021440.Trampoline<RoR2.CharacterBody::FixedUpdate>?1785280512 (RoR2.CharacterBody ) (at <fd1354a948e943be89a0e3e09383a15e>:0)
Rein.RogueWispPlugin.Main.FixedUpdate_On (ReinCore.HooksCore+RoR2+CharacterBody+FixedUpdate+Orig orig, RoR2.CharacterBody self) (at <303810a2b0bf4a69aa9f57986f34d3e0>:0)
DMD<>?-1085021440.Hook<RoR2.CharacterBody::FixedUpdate>?1834140288 (RoR2.CharacterBody ) (at <d9dc1ca032a84dfabbf756480065043b>:0)

**Comment by MapleWheels** [comment]
Thanks for reporting this. Would you kindly give me your `LogOutput.txt`? It has other information that's useful to me, including the active plugins.

**Comment by fwenny** [comment]
Sure, here.
[LogOutput.log](https://github.com/MapleWheels/RoR2_QoLChanges/files/5259792/LogOutput.log)

**Comment by MapleWheels** [comment]
Thanks. This will be fixed in 0.4.

**Comment by MapleWheels** [comment]
Issue has been fixed and will ship with 0.4.
