### ISSUE TITLE
Commando Grenade Damage Not Increasing

### ISSUE THREAD

**Issue by Undead-Tech** [MapleWheels/RoR2_QoLChanges#9]
Title: The damage boost doesn't seem to apply at all, I disabled mods I thought might of conflicted and even set the damage to 500 instead of 10 so I'd know 100% if it was working and I saw no change. No errors seem to appear in the console.
[LogOutput.log](https://github.com/MapleWheels/RoR2_QoLChanges/files/5287015/LogOutput.log)

**Comment by MapleWheels** [comment]
I'll look into this, it appears this is the case.

**Comment by MapleWheels** [comment]
This issue has been fixed in 0.4.
